function setSquareInfo(piece = null, isSelected = false) {
  return { piece, isSelected };
}

export default {
  a8: setSquareInfo('b-rook'),
  b8: setSquareInfo('b-knight'),
  c8: setSquareInfo('b-bishop'),
  d8: setSquareInfo('b-queen'),
  e8: setSquareInfo('b-king'),
  f8: setSquareInfo('b-bishop'),
  g8: setSquareInfo('b-knight'),
  h8: setSquareInfo('b-rook'),
  z8: setSquareInfo(),
  
  a7: setSquareInfo('b-pawn'),
  b7: setSquareInfo('b-pawn'),
  c7: setSquareInfo('b-pawn'),
  d7: setSquareInfo('b-pawn'),
  e7: setSquareInfo('b-pawn'),
  f7: setSquareInfo('b-pawn'),
  g7: setSquareInfo('b-pawn'),
  h7: setSquareInfo('b-pawn'),
  z7: setSquareInfo(),

  a6: setSquareInfo(),
  b6: setSquareInfo(),
  c6: setSquareInfo(),
  d6: setSquareInfo(),
  e6: setSquareInfo(),
  f6: setSquareInfo(),
  g6: setSquareInfo(),
  h6: setSquareInfo(),
  z6: setSquareInfo(),

  a5: setSquareInfo(),
  b5: setSquareInfo(),
  c5: setSquareInfo(),
  d5: setSquareInfo(),
  e5: setSquareInfo(),
  f5: setSquareInfo(),
  g5: setSquareInfo(),
  h5: setSquareInfo(),
  z5: setSquareInfo(),
  
  a4: setSquareInfo(),
  b4: setSquareInfo(),
  c4: setSquareInfo(),
  d4: setSquareInfo(),
  e4: setSquareInfo(),
  f4: setSquareInfo(),
  g4: setSquareInfo(),
  h4: setSquareInfo(),
  z4: setSquareInfo(),
  
  a3: setSquareInfo(),
  b3: setSquareInfo(),
  c3: setSquareInfo(),
  d3: setSquareInfo(),
  e3: setSquareInfo(),
  f3: setSquareInfo(),
  g3: setSquareInfo(),
  h3: setSquareInfo(),
  z3: setSquareInfo(),

  a2: setSquareInfo('w-pawn'),
  b2: setSquareInfo('w-pawn'),
  c2: setSquareInfo('w-pawn'),
  d2: setSquareInfo('w-pawn'),
  e2: setSquareInfo('w-pawn'),
  f2: setSquareInfo('w-pawn'),
  g2: setSquareInfo('w-pawn'),
  h2: setSquareInfo('w-pawn'),
  z2: setSquareInfo(),
  
  a1: setSquareInfo('w-rook'),
  b1: setSquareInfo('w-knight'),
  c1: setSquareInfo('w-bishop'),
  d1: setSquareInfo('w-queen'),
  e1: setSquareInfo('w-king'),
  f1: setSquareInfo('w-bishop'),
  g1: setSquareInfo('w-knight'),
  h1: setSquareInfo('w-rook'),
  z1: setSquareInfo()
};